name: PR Comment Auto Modify
on:
  issue_comment:
    types: [created, edited]  # 當有新的評論創建時觸發
  pull_request_review_comment:
    types: [created, edited]
jobs:
  auto-modify:
    if: > 
      github.event.issue.pull_request && 
      (contains(github.event.comment.body, '添加修改') || 
       contains(github.event.comment.body, '重新修改') || 
       contains(github.event.comment.body, '刪除修改'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # 確保可以推送回遠端
          fetch-depth: 0
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Auto Modify Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ENDPOINT_URL: ${{ secrets.OPENAI_ENDPOINT_URL }}
        run: python auto_mod_tool.py

      - name: Push to branch
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # 確保可以推送回遠端
          fetch-depth: 0
      - run: |
          git push
