name: PR Comment Auto Modify
on:
  issue_comment:
    types: [created]  # 當有新的評論創建時觸發
  pull_request_review_comment:
    types: [created]
jobs:
  auto-modify:
    if: github.event.issue.pull_request || github.event.pull_request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name "Auto Mod Bot"
          git config --global user.email "bot@example.com"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Auto Modify Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ENDPOINT_URL: ${{ secrets.OPENAI_ENDPOINT_URL }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python auto_mod_tool.py
